name: Experimental

on:
  push:
    branches: ['master']
    paths:
      - 'experimental/**'
      - '.github/workflows/experimental.yml'
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'experimental/**'
      - '.github/workflows/experimental.yml'

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: experimental

    # To use Turborepo Remote Caching, set the following environment variables for the job.
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: 'experimental/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            ./experimental/dist/
            ./experimental/package.json
